// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title TragedyBurning
 * @notice Individual SVG contract for Burning effect
 */
contract TragedyBurning {
    function getSVG() external pure returns (string memory) {
        return string(abi.encodePacked(
            '<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><defs><filter id=\"pixelate\"><feFlood x=\"0\" y=\"0\" width=\"1\" height=\"1\" flood-color=\"#E0FFFF\"/><feComposite in2=\"SourceGraphic\" operator=\"over\"/></filter></defs><g><g><g><rect x=\"0.3\" y=\"1.4\" width=\"3\" height=\"2\" fill=\"#FFFF00\"><animate attributeName=\"fill\" values=\"#FFFF00;#FFFAF0;#FFFF00\" dur=\"0.6s\" repeatCount=\"indefinite\"/></rect><rect x=\"0.2\" y=\"1.6\" width=\"4\" height=\"2\" fill=\"#FFD700\"><animate attributeName=\"fill\" values=\"#FFD700;#FFFF00;#FFD700\" dur=\"0.8s\" repeatCount=\"indefinite\"/></rect><rect x=\"0.1\" y=\"1.8\" width=\"6\" height=\"2\" fill=\"#FFA500\"><animate attributeName=\"opacity\" values=\"0.8;1;0.8\" dur=\"1.1s\" repeatCount=\"indefinite\"/></rect><rect x=\"0.2\" y=\"2\" width=\"4\" height=\"2\" fill=\"#FF8C00\"><animate attributeName=\"width\" v',
            'alues=\"4;5;3;4\" dur=\"1.3s\" repeatCount=\"indefinite\"/><animate attributeName=\"x\" values=\"2;1;2;2\" dur=\"1.3s\" repeatCount=\"indefinite\"/></rect><rect x=\"0\" y=\"2.2\" width=\"8\" height=\"2\" fill=\"#FF4500\"><animate attributeName=\"opacity\" values=\"0.6;0.9;0.6\" dur=\"1.4s\" repeatCount=\"indefinite\"/></rect></g><g><rect x=\"1.1\" y=\"1.8\" width=\"2\" height=\"2\" fill=\"#FFFF00\"><animate attributeName=\"fill\" values=\"#FFFF00;#FFFAF0;#FFFF00\" dur=\"0.5s\" begin=\"0.2s\" repeatCount=\"indefinite\"/></rect><rect x=\"1\" y=\"2\" width=\"4\" height=\"2\" fill=\"#FFD700\"><animate attributeName=\"fill\" values=\"#FFD700;#FFFF00;#FFD700\" dur=\"0.7s\" begin=\"0.2s\" repeatCount=\"indefinite\"/></rect><rect x=\"0.8\" y=\"2.2\" width=\"8\" height=\"2\" fill=\"#FFA500\"><animate attributeName=\"opacity\" values=\"0.8;1;0.8\" dur=\"1s\" begin=\"0.2s\" repeatCount=\"i',
            'ndefinite\"/></rect><rect x=\"1\" y=\"2\" width=\"2\" height=\"1\" fill=\"#FF8C00\"><animate attributeName=\"width\" values=\"4;5;3;4\" dur=\"1.2s\" begin=\"0.2s\" repeatCount=\"indefinite\"/><animate attributeName=\"x\" values=\"10;9;10;10\" dur=\"1.2s\" begin=\"0.2s\" repeatCount=\"indefinite\"/></rect><rect x=\"0.8\" y=\"2.7\" width=\"8\" height=\"0\" fill=\"#FF4500\"><animate attributeName=\"opacity\" values=\"0.6;0.9;0.6\" dur=\"1.3s\" begin=\"0.2s\" repeatCount=\"indefinite\"/></rect><rect x=\"1.2\" y=\"2\" width=\"1\" height=\"1\" fill=\"#FFFF00\"><animate attributeName=\"x\" values=\"12;11;12;13;12\" dur=\"2s\" begin=\"0.2s\" repeatCount=\"indefinite\"/><animate attributeName=\"opacity\" values=\"0;1;0.8;1;0\" dur=\"2s\" begin=\"0.2s\" repeatCount=\"indefinite\"/></rect></g><g><rect x=\"1.9\" y=\"1.6\" width=\"2\" height=\"2\" fill=\"#FFFF00\"><animate attributeName=\"fil',
            'l\" values=\"#FFFF00;#FFFAF0;#FFFF00\" dur=\"0.7s\" begin=\"0.4s\" repeatCount=\"indefinite\"/></rect><rect x=\"1.8\" y=\"1.7\" width=\"4\" height=\"2\" fill=\"#FFD700\"><animate attributeName=\"fill\" values=\"#FFD700;#FFFF00;#FFD700\" dur=\"0.9s\" begin=\"0.4s\" repeatCount=\"indefinite\"/></rect><rect x=\"1.7\" y=\"1.9\" width=\"6\" height=\"2\" fill=\"#FFA500\"><animate attributeName=\"opacity\" values=\"0.8;1;0.8\" dur=\"1.2s\" begin=\"0.4s\" repeatCount=\"indefinite\"/></rect><rect x=\"1.8\" y=\"2.1\" width=\"4\" height=\"1\" fill=\"#FF8C00\"><animate attributeName=\"width\" values=\"4;5;3;4\" dur=\"1.4s\" begin=\"0.4s\" repeatCount=\"indefinite\"/><animate attributeName=\"x\" values=\"18;17;18;18\" dur=\"1.4s\" begin=\"0.4s\" repeatCount=\"indefinite\"/></rect><rect x=\"1.6\" y=\"2.2\" width=\"8\" height=\"2\" fill=\"#FF4500\"><animate attributeName=\"opacity\" values=\"0.',
            '6;0.9;0.6\" dur=\"1.5s\" begin=\"0.4s\" repeatCount=\"indefinite\"/></rect></g><rect x=\"0.5\" y=\"1.2\" width=\"1\" height=\"1\" fill=\"#FFA500\"><animate attributeName=\"y\" values=\"18;12;8\" dur=\"2s\" repeatCount=\"indefinite\"/><animate attributeName=\"opacity\" values=\"0;0.8;0\" dur=\"2s\" repeatCount=\"indefinite\"/></rect><rect x=\"1.2\" y=\"1\" width=\"1\" height=\"1\" fill=\"#FF8C00\"><animate attributeName=\"y\" values=\"16;10;6\" dur=\"2.2s\" begin=\"0.5s\" repeatCount=\"indefinite\"/><animate attributeName=\"opacity\" values=\"0;0.6;0\" dur=\"2.2s\" begin=\"0.5s\" repeatCount=\"indefinite\"/></rect><rect x=\"2\" y=\"1.1\" width=\"1\" height=\"1\" fill=\"#FFFF00\"><animate attributeName=\"y\" values=\"17;11;7\" dur=\"2.4s\" begin=\"1s\" repeatCount=\"indefinite\"/><animate attributeName=\"opacity\" values=\"0;0.7;0\" dur=\"2.4s\" begin=\"1s\" repeatCount=\"indefinit',
            'e\"/></rect></g></g></svg>'
        ));
    }
}